# Uncomment the next line to define a global platform for your project
platform :osx, '10.12'

target 'Testbed' do
  use_frameworks!
  pod 'Alamofire'
  pod 'SwaggerClientSupport', :path => 'DevelopmentPods/SwaggerClientSupport'
  pod 'IdentityApi', :path => 'DevelopmentPods/Generated'
  pod 'LovesApi', :path => 'DevelopmentPods/Generated'
  pod 'LoyaltyApi', :path => 'DevelopmentPods/Generated'
  pod 'MobileOrchestrationApi', :path => 'DevelopmentPods/Generated'
  pod 'PaymentApi', :path => 'DevelopmentPods/Generated'
  pod 'VehicleApi', :path => 'DevelopmentPods/Generated'
end
